# Site settings
title: A blog about lorem ipsum dolor sit amet
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "http://khj3535.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: KIM HYOUNG JUN
user_description: HyoungJun's Blog
user_title: Web Developer
email: rlagudwns3555@gmail.com
twitter_username: KHJ
github_username:  KHJ3535
gplus_username:  KHJ

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
